code:
	claude

continue:
	claude code continue

install:
	uv pip install -r requirements.txt

deploy:
	modal deploy backend/services/acord_api.py
	modal deploy backend/services/geocodable_address_api.py